// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.AccessrequestDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.RiskinformationSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskinformationProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserActionProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import java.util.Set;

public abstract class AccessrequestMobileDetailsView_Roo_Gwt extends Composite implements AccessrequestDetailsView {

    @UiField
    Element accessrequestId;

    @UiField
    Element riskinformations;

    @UiField
    Element assetId;

    @UiField
    Element opportunityId;

    @UiField
    Element deviceId;

    @UiField
    Element userId;

    @UiField
    Element riskcommunicationid;

    @UiField
    Element threatid;

    @UiField
    Element useractionId;

    @UiField
    Element solved;

    @UiField
    Element ttl;

    AccessrequestProxy proxy;

    public void setValue(AccessrequestProxy proxy) {
        this.proxy = proxy;
        accessrequestId.setInnerText(proxy.getAccessrequestId() == null ? "" : String.valueOf(proxy.getAccessrequestId()));
        riskinformations.setInnerText(proxy.getRiskinformations() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.RiskinformationProxyRenderer.instance()).render(proxy.getRiskinformations()));
        assetId.setInnerText(proxy.getAssetId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.AssetProxyRenderer.instance().render(proxy.getAssetId()));
        opportunityId.setInnerText(proxy.getOpportunityId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.OpportunityProxyRenderer.instance().render(proxy.getOpportunityId()));
        deviceId.setInnerText(proxy.getDeviceId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.DeviceProxyRenderer.instance().render(proxy.getDeviceId()));
        userId.setInnerText(proxy.getUserId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.UserProxyRenderer.instance().render(proxy.getUserId()));
        riskcommunicationid.setInnerText(proxy.getRiskcommunicationid() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.RiskcommunicationProxyRenderer.instance().render(proxy.getRiskcommunicationid()));
        threatid.setInnerText(proxy.getThreatid() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.ThreatProxyRenderer.instance().render(proxy.getThreatid()));
        useractionId.setInnerText(proxy.getUseractionId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.UserActionProxyRenderer.instance().render(proxy.getUseractionId()));
        solved.setInnerText(proxy.getSolved() == null ? "" : String.valueOf(proxy.getSolved()));
        ttl.setInnerText(proxy.getTtl() == null ? "" : String.valueOf(proxy.getTtl()));
    }
}
