// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.AssetDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.RiskinformationSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.SecurityIncidentSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskinformationProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import java.util.Set;

public abstract class AssetMobileDetailsView_Roo_Gwt extends Composite implements AssetDetailsView {

    @UiField
    Element assetId;

    @UiField
    Element accessrequests;

    @UiField
    Element riskinformations;

    @UiField
    Element securityIncidents;

    @UiField
    Element opportunityid;

    @UiField
    Element assetName;

    @UiField
    Element description;

    @UiField
    Element value;

    @UiField
    Element confidentialLevel;

    @UiField
    Element location;

    AssetProxy proxy;

    public void setValue(AssetProxy proxy) {
        this.proxy = proxy;
        assetId.setInnerText(proxy.getAssetId() == null ? "" : String.valueOf(proxy.getAssetId()));
        accessrequests.setInnerText(proxy.getAccessrequests() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance()).render(proxy.getAccessrequests()));
        riskinformations.setInnerText(proxy.getRiskinformations() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.RiskinformationProxyRenderer.instance()).render(proxy.getRiskinformations()));
        securityIncidents.setInnerText(proxy.getSecurityIncidents() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.SecurityIncidentProxyRenderer.instance()).render(proxy.getSecurityIncidents()));
        opportunityid.setInnerText(proxy.getOpportunityid() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.OpportunityProxyRenderer.instance().render(proxy.getOpportunityid()));
        assetName.setInnerText(proxy.getAssetName() == null ? "" : String.valueOf(proxy.getAssetName()));
        description.setInnerText(proxy.getDescription() == null ? "" : String.valueOf(proxy.getDescription()));
        value.setInnerText(proxy.getValue() == null ? "" : String.valueOf(proxy.getValue()));
        confidentialLevel.setInnerText(proxy.getConfidentialLevel() == null ? "" : String.valueOf(proxy.getConfidentialLevel()));
        location.setInnerText(proxy.getLocation() == null ? "" : String.valueOf(proxy.getLocation()));
    }
}
