// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import eu.musesproject.server.rt2ae.client.managed.activity.OutcomeEditActivityWrapper;
import eu.musesproject.server.rt2ae.client.managed.activity.OutcomeEditActivityWrapper.View;
import eu.musesproject.server.rt2ae.client.managed.ui.OutcomeEditView;
import eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy;
import eu.musesproject.server.rt2ae.client.proxy.OutcomeProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyEditView;
import eu.musesproject.server.rt2ae.client.scaffold.ui.*;
import java.util.Collection;
import java.util.List;

public abstract class OutcomeMobileEditView_Roo_Gwt extends Composite implements View<OutcomeMobileEditView> {

    @UiField(provided = true)
    ValueListBox<OpportunityProxy> opportunityId = new ValueListBox<OpportunityProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.OpportunityProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy>());

    @UiField(provided = true)
    ValueListBox<ThreatProxy> threatId = new ValueListBox<ThreatProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.ThreatProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.ThreatProxy>());

    @UiField
    TextBox description;

    @UiField
    DoubleBox costbenefit;

    public void setOpportunityIdPickerValues(Collection<OpportunityProxy> values) {
        opportunityId.setAcceptableValues(values);
    }

    public void setThreatIdPickerValues(Collection<ThreatProxy> values) {
        threatId.setAcceptableValues(values);
    }
}
