// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.RiskinformationDetailsView;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskinformationProxy;

public abstract class RiskinformationMobileDetailsView_Roo_Gwt extends Composite implements RiskinformationDetailsView {

    @UiField
    Element riskinformationId;

    @UiField
    Element accessrequestId;

    @UiField
    Element assetId;

    @UiField
    Element type;

    @UiField
    Element description;

    @UiField
    Element probability;

    RiskinformationProxy proxy;

    public void setValue(RiskinformationProxy proxy) {
        this.proxy = proxy;
        riskinformationId.setInnerText(proxy.getRiskinformationId() == null ? "" : String.valueOf(proxy.getRiskinformationId()));
        accessrequestId.setInnerText(proxy.getAccessrequestId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance().render(proxy.getAccessrequestId()));
        assetId.setInnerText(proxy.getAssetId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.AssetProxyRenderer.instance().render(proxy.getAssetId()));
        type.setInnerText(proxy.getType() == null ? "" : String.valueOf(proxy.getType()));
        description.setInnerText(proxy.getDescription() == null ? "" : String.valueOf(proxy.getDescription()));
        probability.setInnerText(proxy.getProbability() == null ? "" : String.valueOf(proxy.getProbability()));
    }
}
