// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import eu.musesproject.server.rt2ae.client.managed.activity.SecurityIncidentEditActivityWrapper;
import eu.musesproject.server.rt2ae.client.managed.activity.SecurityIncidentEditActivityWrapper.View;
import eu.musesproject.server.rt2ae.client.managed.ui.SecurityIncidentEditView;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyEditView;
import eu.musesproject.server.rt2ae.client.scaffold.ui.*;
import java.util.Collection;
import java.util.List;

public abstract class SecurityIncidentMobileEditView_Roo_Gwt extends Composite implements View<SecurityIncidentMobileEditView> {

    @UiField(provided = true)
    ValueListBox<AssetProxy> assetsId = new ValueListBox<AssetProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AssetProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.AssetProxy>());

    @UiField(provided = true)
    ValueListBox<DeviceProxy> devicesId = new ValueListBox<DeviceProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.DeviceProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.DeviceProxy>());

    @UiField(provided = true)
    ValueListBox<UserProxy> usersId = new ValueListBox<UserProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.UserProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.UserProxy>());

    @UiField
    TextBox description;

    @UiField
    DoubleBox costbenefit;

    @UiField
    IntegerBox decisionId;

    @UiField
    DoubleBox probability;

    public void setUsersIdPickerValues(Collection<UserProxy> values) {
        usersId.setAcceptableValues(values);
    }

    public void setDevicesIdPickerValues(Collection<DeviceProxy> values) {
        devicesId.setAcceptableValues(values);
    }

    public void setAssetsIdPickerValues(Collection<AssetProxy> values) {
        assetsId.setAcceptableValues(values);
    }
}
