// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.ClueDetailsView;
import eu.musesproject.server.rt2ae.client.proxy.ClueProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListView;

public abstract class ClueDesktopDetailsView_Roo_Gwt extends Composite implements ClueDetailsView {

    @UiField
    SpanElement clueId;

    @UiField
    SpanElement threatId;

    @UiField
    SpanElement value;

    ClueProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(ClueProxy proxy) {
        this.proxy = proxy;
        clueId.setInnerText(proxy.getClueId() == null ? "" : String.valueOf(proxy.getClueId()));
        threatId.setInnerText(proxy.getThreatId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.ThreatProxyRenderer.instance().render(proxy.getThreatId()));
        value.setInnerText(proxy.getValue() == null ? "" : String.valueOf(proxy.getValue()));
        displayRenderer.setInnerText(eu.musesproject.server.rt2ae.client.managed.ui.renderer.ClueProxyRenderer.instance().render(proxy));
    }
}
