// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.DecisionDetailsView;
import eu.musesproject.server.rt2ae.client.proxy.DecisionProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListView;

public abstract class DecisionDesktopDetailsView_Roo_Gwt extends Composite implements DecisionDetailsView {

    @UiField
    SpanElement decisionId;

    @UiField
    SpanElement riskcommunicationId;

    @UiField
    SpanElement value;

    DecisionProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(DecisionProxy proxy) {
        this.proxy = proxy;
        decisionId.setInnerText(proxy.getDecisionId() == null ? "" : String.valueOf(proxy.getDecisionId()));
        riskcommunicationId.setInnerText(proxy.getRiskcommunicationId() == null ? "" : eu.musesproject.server.rt2ae.client.managed.ui.renderer.RiskcommunicationProxyRenderer.instance().render(proxy.getRiskcommunicationId()));
        value.setInnerText(proxy.getValue() == null ? "" : String.valueOf(proxy.getValue()));
        displayRenderer.setInnerText(eu.musesproject.server.rt2ae.client.managed.ui.renderer.DecisionProxyRenderer.instance().render(proxy));
    }
}
