// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import eu.musesproject.server.rt2ae.client.proxy.DecisionProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.AbstractProxyListView;
import java.util.HashSet;
import java.util.Set;

public abstract class DecisionDesktopListView_Roo_Gwt extends AbstractProxyListView<DecisionProxy> {

    @UiField
    CellTable<DecisionProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("decisionId");
        table.addColumn(new TextColumn<DecisionProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DecisionProxy object) {
                return renderer.render(object.getDecisionId());
            }
        }, "Decision Id");
        paths.add("riskcommunicationId");
        table.addColumn(new TextColumn<DecisionProxy>() {

            Renderer<eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy> renderer = eu.musesproject.server.rt2ae.client.managed.ui.renderer.RiskcommunicationProxyRenderer.instance();

            @Override
            public String getValue(DecisionProxy object) {
                return renderer.render(object.getRiskcommunicationId());
            }
        }, "Riskcommunication Id");
        paths.add("value");
        table.addColumn(new TextColumn<DecisionProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DecisionProxy object) {
                return renderer.render(object.getValue());
            }
        }, "Value");
    }
}
