// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import eu.musesproject.server.rt2ae.client.managed.activity.DeviceEditActivityWrapper;
import eu.musesproject.server.rt2ae.client.managed.activity.DeviceEditActivityWrapper.View;
import eu.musesproject.server.rt2ae.client.managed.ui.DeviceEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.DeviceSecurityStateSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.SecurityIncidentSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceSecurityStateProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import java.util.Collection;
import java.util.List;
import java.util.Set;

public abstract class DeviceDesktopEditView_Roo_Gwt extends Composite implements View<DeviceDesktopEditView> {

    @UiField
    AccessrequestSetEditor accessrequests;

    @UiField
    DeviceSecurityStateSetEditor deviceSecurityStates;

    @UiField
    SecurityIncidentSetEditor securityIncidents;

    @UiField(provided = true)
    ValueListBox<UserProxy> ownerId = new ValueListBox<UserProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.UserProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.UserProxy>());

    @UiField
    TextBox name;

    @UiField
    TextBox type;

    @UiField
    TextBox description;

    @UiField
    TextBox imei;

    @UiField
    TextBox macaddress;

    @UiField
    TextBox os;

    @UiField
    TextBox trustvalue;

    public void setSecurityIncidentsPickerValues(Collection<SecurityIncidentProxy> values) {
        securityIncidents.setAcceptableValues(values);
    }

    public void setOwnerIdPickerValues(Collection<UserProxy> values) {
        ownerId.setAcceptableValues(values);
    }

    public void setAccessrequestsPickerValues(Collection<AccessrequestProxy> values) {
        accessrequests.setAcceptableValues(values);
    }

    public void setDeviceSecurityStatesPickerValues(Collection<DeviceSecurityStateProxy> values) {
        deviceSecurityStates.setAcceptableValues(values);
    }
}
