// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceSecurityStateProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.AbstractProxyListView;
import java.util.HashSet;
import java.util.Set;

public abstract class DeviceSecurityStateDesktopListView_Roo_Gwt extends AbstractProxyListView<DeviceSecurityStateProxy> {

    @UiField
    CellTable<DeviceSecurityStateProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("deviceSecurityStateId");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getDeviceSecurityStateId());
            }
        }, "Device Security State Id");
        paths.add("deviceId");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<eu.musesproject.server.rt2ae.client.proxy.DeviceProxy> renderer = eu.musesproject.server.rt2ae.client.managed.ui.renderer.DeviceProxyRenderer.instance();

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getDeviceId());
            }
        }, "Device Id");
        paths.add("devicestate");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getDevicestate());
            }
        }, "Devicestate");
        paths.add("antivirus");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getAntivirus());
            }
        }, "Antivirus");
        paths.add("passwordprotection");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getPasswordprotection());
            }
        }, "Passwordprotection");
        paths.add("autolock");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getAutolock());
            }
        }, "Autolock");
        paths.add("sslprotection");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getSslprotection());
            }
        }, "Sslprotection");
        paths.add("encryption");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getEncryption());
            }
        }, "Encryption");
        paths.add("trackingdevice");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getTrackingdevice());
            }
        }, "Trackingdevice");
        paths.add("remotewipe");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getRemotewipe());
            }
        }, "Remotewipe");
        paths.add("vpn");
        table.addColumn(new TextColumn<DeviceSecurityStateProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(DeviceSecurityStateProxy object) {
                return renderer.render(object.getVpn());
            }
        }, "Vpn");
    }
}
