// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy;
import eu.musesproject.server.rt2ae.client.proxy.OutcomeProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.AbstractProxyListView;
import java.util.HashSet;
import java.util.Set;

public abstract class OutcomeDesktopListView_Roo_Gwt extends AbstractProxyListView<OutcomeProxy> {

    @UiField
    CellTable<OutcomeProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("outcomeId");
        table.addColumn(new TextColumn<OutcomeProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(OutcomeProxy object) {
                return renderer.render(object.getOutcomeId());
            }
        }, "Outcome Id");
        paths.add("opportunityId");
        table.addColumn(new TextColumn<OutcomeProxy>() {

            Renderer<eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy> renderer = eu.musesproject.server.rt2ae.client.managed.ui.renderer.OpportunityProxyRenderer.instance();

            @Override
            public String getValue(OutcomeProxy object) {
                return renderer.render(object.getOpportunityId());
            }
        }, "Opportunity Id");
        paths.add("threatId");
        table.addColumn(new TextColumn<OutcomeProxy>() {

            Renderer<eu.musesproject.server.rt2ae.client.proxy.ThreatProxy> renderer = eu.musesproject.server.rt2ae.client.managed.ui.renderer.ThreatProxyRenderer.instance();

            @Override
            public String getValue(OutcomeProxy object) {
                return renderer.render(object.getThreatId());
            }
        }, "Threat Id");
        paths.add("description");
        table.addColumn(new TextColumn<OutcomeProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(OutcomeProxy object) {
                return renderer.render(object.getDescription());
            }
        }, "Description");
        paths.add("costbenefit");
        table.addColumn(new TextColumn<OutcomeProxy>() {

            Renderer<java.lang.Double> renderer = new AbstractRenderer<java.lang.Double>() {

                public String render(java.lang.Double obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(OutcomeProxy object) {
                return renderer.render(object.getCostbenefit());
            }
        }, "Costbenefit");
    }
}
