// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.RiskcommunicationDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.DecisionSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.RisktreatmentSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.DecisionProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy;
import eu.musesproject.server.rt2ae.client.proxy.RisktreatmentProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListView;
import java.util.Set;

public abstract class RiskcommunicationDesktopDetailsView_Roo_Gwt extends Composite implements RiskcommunicationDetailsView {

    @UiField
    SpanElement riskcommunicationId;

    @UiField
    SpanElement accessrequests;

    @UiField
    SpanElement decisions;

    @UiField
    SpanElement risktreatments;

    @UiField
    SpanElement textualDescription;

    RiskcommunicationProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(RiskcommunicationProxy proxy) {
        this.proxy = proxy;
        riskcommunicationId.setInnerText(proxy.getRiskcommunicationId() == null ? "" : String.valueOf(proxy.getRiskcommunicationId()));
        accessrequests.setInnerText(proxy.getAccessrequests() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance()).render(proxy.getAccessrequests()));
        decisions.setInnerText(proxy.getDecisions() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.DecisionProxyRenderer.instance()).render(proxy.getDecisions()));
        risktreatments.setInnerText(proxy.getRisktreatments() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.RisktreatmentProxyRenderer.instance()).render(proxy.getRisktreatments()));
        textualDescription.setInnerText(proxy.getTextualDescription() == null ? "" : String.valueOf(proxy.getTextualDescription()));
        displayRenderer.setInnerText(eu.musesproject.server.rt2ae.client.managed.ui.renderer.RiskcommunicationProxyRenderer.instance().render(proxy));
    }
}
