// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import eu.musesproject.server.rt2ae.client.managed.activity.RiskinformationEditActivityWrapper;
import eu.musesproject.server.rt2ae.client.managed.activity.RiskinformationEditActivityWrapper.View;
import eu.musesproject.server.rt2ae.client.managed.ui.RiskinformationEditView;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskinformationProxy;
import java.util.Collection;
import java.util.List;

public abstract class RiskinformationDesktopEditView_Roo_Gwt extends Composite implements View<RiskinformationDesktopEditView> {

    @UiField(provided = true)
    ValueListBox<AccessrequestProxy> accessrequestId = new ValueListBox<AccessrequestProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy>());

    @UiField(provided = true)
    ValueListBox<AssetProxy> assetId = new ValueListBox<AssetProxy>(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AssetProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<eu.musesproject.server.rt2ae.client.proxy.AssetProxy>());

    @UiField
    TextBox type;

    @UiField
    TextBox description;

    @UiField
    DoubleBox probability;

    public void setAssetIdPickerValues(Collection<AssetProxy> values) {
        assetId.setAcceptableValues(values);
    }

    public void setAccessrequestIdPickerValues(Collection<AccessrequestProxy> values) {
        accessrequestId.setAcceptableValues(values);
    }
}
