// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskinformationProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.AbstractProxyListView;
import java.util.HashSet;
import java.util.Set;

public abstract class RiskinformationDesktopListView_Roo_Gwt extends AbstractProxyListView<RiskinformationProxy> {

    @UiField
    CellTable<RiskinformationProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("riskinformationId");
        table.addColumn(new TextColumn<RiskinformationProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RiskinformationProxy object) {
                return renderer.render(object.getRiskinformationId());
            }
        }, "Riskinformation Id");
        paths.add("accessrequestId");
        table.addColumn(new TextColumn<RiskinformationProxy>() {

            Renderer<eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy> renderer = eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance();

            @Override
            public String getValue(RiskinformationProxy object) {
                return renderer.render(object.getAccessrequestId());
            }
        }, "Accessrequest Id");
        paths.add("assetId");
        table.addColumn(new TextColumn<RiskinformationProxy>() {

            Renderer<eu.musesproject.server.rt2ae.client.proxy.AssetProxy> renderer = eu.musesproject.server.rt2ae.client.managed.ui.renderer.AssetProxyRenderer.instance();

            @Override
            public String getValue(RiskinformationProxy object) {
                return renderer.render(object.getAssetId());
            }
        }, "Asset Id");
        paths.add("type");
        table.addColumn(new TextColumn<RiskinformationProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RiskinformationProxy object) {
                return renderer.render(object.getType());
            }
        }, "Type");
        paths.add("description");
        table.addColumn(new TextColumn<RiskinformationProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RiskinformationProxy object) {
                return renderer.render(object.getDescription());
            }
        }, "Description");
        paths.add("probability");
        table.addColumn(new TextColumn<RiskinformationProxy>() {

            Renderer<java.lang.Double> renderer = new AbstractRenderer<java.lang.Double>() {

                public String render(java.lang.Double obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RiskinformationProxy object) {
                return renderer.render(object.getProbability());
            }
        }, "Probability");
    }
}
