// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.ThreatDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.ClueSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.OutcomeSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.ClueProxy;
import eu.musesproject.server.rt2ae.client.proxy.OutcomeProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListView;
import java.util.Set;

public abstract class ThreatDesktopDetailsView_Roo_Gwt extends Composite implements ThreatDetailsView {

    @UiField
    SpanElement threatId;

    @UiField
    SpanElement accessrequests;

    @UiField
    SpanElement clues;

    @UiField
    SpanElement outcomes;

    @UiField
    SpanElement description;

    @UiField
    SpanElement probability;

    @UiField
    SpanElement occurences;

    @UiField
    SpanElement badOutcomeCount;

    ThreatProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(ThreatProxy proxy) {
        this.proxy = proxy;
        threatId.setInnerText(proxy.getThreatId() == null ? "" : String.valueOf(proxy.getThreatId()));
        accessrequests.setInnerText(proxy.getAccessrequests() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance()).render(proxy.getAccessrequests()));
        clues.setInnerText(proxy.getClues() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.ClueProxyRenderer.instance()).render(proxy.getClues()));
        outcomes.setInnerText(proxy.getOutcomes() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.OutcomeProxyRenderer.instance()).render(proxy.getOutcomes()));
        description.setInnerText(proxy.getDescription() == null ? "" : String.valueOf(proxy.getDescription()));
        probability.setInnerText(proxy.getProbability() == null ? "" : String.valueOf(proxy.getProbability()));
        occurences.setInnerText(proxy.getOccurences() == null ? "" : String.valueOf(proxy.getOccurences()));
        badOutcomeCount.setInnerText(proxy.getBadOutcomeCount() == null ? "" : String.valueOf(proxy.getBadOutcomeCount()));
        displayRenderer.setInnerText(eu.musesproject.server.rt2ae.client.managed.ui.renderer.ThreatProxyRenderer.instance().render(proxy));
    }
}
