// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.ClueSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.OutcomeSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.ClueProxy;
import eu.musesproject.server.rt2ae.client.proxy.OutcomeProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.AbstractProxyListView;
import java.util.HashSet;
import java.util.Set;

public abstract class ThreatDesktopListView_Roo_Gwt extends AbstractProxyListView<ThreatProxy> {

    @UiField
    CellTable<ThreatProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("threatId");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getThreatId());
            }
        }, "Threat Id");
        paths.add("accessrequests");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.util.Set> renderer = eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance());

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getAccessrequests());
            }
        }, "Accessrequests");
        paths.add("clues");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.util.Set> renderer = eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.ClueProxyRenderer.instance());

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getClues());
            }
        }, "Clues");
        paths.add("outcomes");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.util.Set> renderer = eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.OutcomeProxyRenderer.instance());

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getOutcomes());
            }
        }, "Outcomes");
        paths.add("description");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getDescription());
            }
        }, "Description");
        paths.add("probability");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.lang.Double> renderer = new AbstractRenderer<java.lang.Double>() {

                public String render(java.lang.Double obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getProbability());
            }
        }, "Probability");
        paths.add("occurences");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.lang.Double> renderer = new AbstractRenderer<java.lang.Double>() {

                public String render(java.lang.Double obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getOccurences());
            }
        }, "Occurences");
        paths.add("badOutcomeCount");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.lang.Double> renderer = new AbstractRenderer<java.lang.Double>() {

                public String render(java.lang.Double obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getBadOutcomeCount());
            }
        }, "Bad Outcome Count");
        paths.add("ttl");
        table.addColumn(new TextColumn<ThreatProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ThreatProxy object) {
                return renderer.render(object.getTtl());
            }
        }, "Ttl");
    }
}
