// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import eu.musesproject.server.rt2ae.client.managed.ui.UserDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.DeviceSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.SecurityIncidentSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListView;
import java.util.Set;

public abstract class UserDesktopDetailsView_Roo_Gwt extends Composite implements UserDetailsView {

    @UiField
    SpanElement userId;

    @UiField
    SpanElement accessrequests;

    @UiField
    SpanElement devices;

    @UiField
    SpanElement securityIncidents;

    @UiField
    SpanElement name;

    @UiField
    SpanElement surname;

    @UiField
    SpanElement email;

    @UiField
    SpanElement trustvalue;

    @UiField
    SpanElement hourlyCost;

    UserProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(UserProxy proxy) {
        this.proxy = proxy;
        userId.setInnerText(proxy.getUserId() == null ? "" : String.valueOf(proxy.getUserId()));
        accessrequests.setInnerText(proxy.getAccessrequests() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance()).render(proxy.getAccessrequests()));
        devices.setInnerText(proxy.getDevices() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.DeviceProxyRenderer.instance()).render(proxy.getDevices()));
        securityIncidents.setInnerText(proxy.getSecurityIncidents() == null ? "" : eu.musesproject.server.rt2ae.client.scaffold.place.CollectionRenderer.of(eu.musesproject.server.rt2ae.client.managed.ui.renderer.SecurityIncidentProxyRenderer.instance()).render(proxy.getSecurityIncidents()));
        name.setInnerText(proxy.getName() == null ? "" : String.valueOf(proxy.getName()));
        surname.setInnerText(proxy.getSurname() == null ? "" : String.valueOf(proxy.getSurname()));
        email.setInnerText(proxy.getEmail() == null ? "" : String.valueOf(proxy.getEmail()));
        trustvalue.setInnerText(proxy.getTrustvalue() == null ? "" : String.valueOf(proxy.getTrustvalue()));
        hourlyCost.setInnerText(proxy.getHourlyCost() == null ? "" : String.valueOf(proxy.getHourlyCost()));
        displayRenderer.setInnerText(eu.musesproject.server.rt2ae.client.managed.ui.renderer.UserProxyRenderer.instance().render(proxy));
    }
}
