// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.musesproject.server.rt2ae;

import eu.musesproject.server.rt2ae.SecurityIncident;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SecurityIncident_Roo_Configurable {
    
    declare @type: SecurityIncident: @Configurable;
    
}
