// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.musesproject.server.rt2ae;

import eu.musesproject.server.rt2ae.Opportunity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Opportunity_Roo_Configurable {
    
    declare @type: Opportunity: @Configurable;
    
}
