// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.AccessrequestDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.AccessrequestDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.AccessrequestDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.RiskinformationSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.AccessrequestMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.AccessrequestMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskinformationProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserActionProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import eu.musesproject.server.rt2ae.client.request.AccessrequestRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.Set;

public abstract class AccessrequestActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        AccessrequestDesktopEditView.instance().setCreating(true);
        Activity activity = new AccessrequestEditActivity(null, factory, ScaffoldApp.isMobile() ? AccessrequestMobileEditView.instance() : AccessrequestDesktopEditView.instance(), placeController);
        return new AccessrequestEditActivityWrapper(factory, ScaffoldApp.isMobile() ? AccessrequestMobileEditView.instance() : AccessrequestDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<AccessrequestProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<AccessrequestProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        AccessrequestDesktopEditView.instance().setCreating(false);
        EntityProxyId<AccessrequestProxy> proxyId = coerceId(place);
        Activity activity = new AccessrequestEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? AccessrequestMobileEditView.instance() : AccessrequestDesktopEditView.instance(), placeController);
        return new AccessrequestEditActivityWrapper(factory, ScaffoldApp.isMobile() ? AccessrequestMobileEditView.instance() : AccessrequestDesktopEditView.instance(), activity, proxyId);
    }
}
