// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.ClueDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.ClueDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.ClueDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.ClueMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.ClueMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.ClueProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.request.ClueRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;

public abstract class ClueActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        ClueDesktopEditView.instance().setCreating(true);
        Activity activity = new ClueEditActivity(null, factory, ScaffoldApp.isMobile() ? ClueMobileEditView.instance() : ClueDesktopEditView.instance(), placeController);
        return new ClueEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ClueMobileEditView.instance() : ClueDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<ClueProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<ClueProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        ClueDesktopEditView.instance().setCreating(false);
        EntityProxyId<ClueProxy> proxyId = coerceId(place);
        Activity activity = new ClueEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? ClueMobileEditView.instance() : ClueDesktopEditView.instance(), placeController);
        return new ClueEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ClueMobileEditView.instance() : ClueDesktopEditView.instance(), activity, proxyId);
    }
}
