// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.DecisionDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.DecisionDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.DecisionDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.DecisionMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.DecisionMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.DecisionProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy;
import eu.musesproject.server.rt2ae.client.request.DecisionRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;

public abstract class DecisionActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        DecisionDesktopEditView.instance().setCreating(true);
        Activity activity = new DecisionEditActivity(null, factory, ScaffoldApp.isMobile() ? DecisionMobileEditView.instance() : DecisionDesktopEditView.instance(), placeController);
        return new DecisionEditActivityWrapper(factory, ScaffoldApp.isMobile() ? DecisionMobileEditView.instance() : DecisionDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<DecisionProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<DecisionProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        DecisionDesktopEditView.instance().setCreating(false);
        EntityProxyId<DecisionProxy> proxyId = coerceId(place);
        Activity activity = new DecisionEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? DecisionMobileEditView.instance() : DecisionDesktopEditView.instance(), placeController);
        return new DecisionEditActivityWrapper(factory, ScaffoldApp.isMobile() ? DecisionMobileEditView.instance() : DecisionDesktopEditView.instance(), activity, proxyId);
    }
}
