// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.DeviceDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.DeviceDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.DeviceDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.DeviceSecurityStateSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.SecurityIncidentSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.DeviceMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.DeviceMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceSecurityStateProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import eu.musesproject.server.rt2ae.client.request.DeviceRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.Set;

public abstract class DeviceActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        DeviceDesktopEditView.instance().setCreating(true);
        Activity activity = new DeviceEditActivity(null, factory, ScaffoldApp.isMobile() ? DeviceMobileEditView.instance() : DeviceDesktopEditView.instance(), placeController);
        return new DeviceEditActivityWrapper(factory, ScaffoldApp.isMobile() ? DeviceMobileEditView.instance() : DeviceDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<DeviceProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<DeviceProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        DeviceDesktopEditView.instance().setCreating(false);
        EntityProxyId<DeviceProxy> proxyId = coerceId(place);
        Activity activity = new DeviceEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? DeviceMobileEditView.instance() : DeviceDesktopEditView.instance(), placeController);
        return new DeviceEditActivityWrapper(factory, ScaffoldApp.isMobile() ? DeviceMobileEditView.instance() : DeviceDesktopEditView.instance(), activity, proxyId);
    }
}
