// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import eu.musesproject.server.rt2ae.client.managed.activity.DeviceEditActivityWrapper.View;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.DeviceEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.DeviceSecurityStateSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.SecurityIncidentSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceSecurityStateProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import eu.musesproject.server.rt2ae.client.scaffold.activity.IsScaffoldMobileActivity;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyEditView;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListPlace;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;

public abstract class DeviceEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setAccessrequestsPickerValues(Collections.<AccessrequestProxy>emptyList());
        requests.accessrequestRequest().findAccessrequestEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance().getPaths()).fire(new Receiver<List<AccessrequestProxy>>() {

            public void onSuccess(List<AccessrequestProxy> response) {
                List<AccessrequestProxy> values = new ArrayList<AccessrequestProxy>();
                values.add(null);
                values.addAll(response);
                view.setAccessrequestsPickerValues(values);
            }
        });
        view.setDeviceSecurityStatesPickerValues(Collections.<DeviceSecurityStateProxy>emptyList());
        requests.deviceSecurityStateRequest().findDeviceSecurityStateEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.DeviceSecurityStateProxyRenderer.instance().getPaths()).fire(new Receiver<List<DeviceSecurityStateProxy>>() {

            public void onSuccess(List<DeviceSecurityStateProxy> response) {
                List<DeviceSecurityStateProxy> values = new ArrayList<DeviceSecurityStateProxy>();
                values.add(null);
                values.addAll(response);
                view.setDeviceSecurityStatesPickerValues(values);
            }
        });
        view.setSecurityIncidentsPickerValues(Collections.<SecurityIncidentProxy>emptyList());
        requests.securityIncidentRequest().findSecurityIncidentEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.SecurityIncidentProxyRenderer.instance().getPaths()).fire(new Receiver<List<SecurityIncidentProxy>>() {

            public void onSuccess(List<SecurityIncidentProxy> response) {
                List<SecurityIncidentProxy> values = new ArrayList<SecurityIncidentProxy>();
                values.add(null);
                values.addAll(response);
                view.setSecurityIncidentsPickerValues(values);
            }
        });
        view.setOwnerIdPickerValues(Collections.<UserProxy>emptyList());
        requests.userRequest().findUserEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.UserProxyRenderer.instance().getPaths()).fire(new Receiver<List<UserProxy>>() {

            public void onSuccess(List<UserProxy> response) {
                List<UserProxy> values = new ArrayList<UserProxy>();
                values.add(null);
                values.addAll(response);
                view.setOwnerIdPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends eu.musesproject.server.rt2ae.client.managed.ui.DeviceEditView<V>> extends DeviceEditView<V> {

        void setAccessrequestsPickerValues(Collection<AccessrequestProxy> values);

        void setDeviceSecurityStatesPickerValues(Collection<DeviceSecurityStateProxy> values);

        void setSecurityIncidentsPickerValues(Collection<SecurityIncidentProxy> values);

        void setOwnerIdPickerValues(Collection<UserProxy> values);
    }
}
