// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.OpportunityDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.OpportunityDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.OpportunityDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AssetSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.OutcomeSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.OpportunityMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.OpportunityMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy;
import eu.musesproject.server.rt2ae.client.proxy.OutcomeProxy;
import eu.musesproject.server.rt2ae.client.request.OpportunityRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.Set;

public abstract class OpportunityActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        OpportunityDesktopEditView.instance().setCreating(true);
        Activity activity = new OpportunityEditActivity(null, factory, ScaffoldApp.isMobile() ? OpportunityMobileEditView.instance() : OpportunityDesktopEditView.instance(), placeController);
        return new OpportunityEditActivityWrapper(factory, ScaffoldApp.isMobile() ? OpportunityMobileEditView.instance() : OpportunityDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<OpportunityProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<OpportunityProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        OpportunityDesktopEditView.instance().setCreating(false);
        EntityProxyId<OpportunityProxy> proxyId = coerceId(place);
        Activity activity = new OpportunityEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? OpportunityMobileEditView.instance() : OpportunityDesktopEditView.instance(), placeController);
        return new OpportunityEditActivityWrapper(factory, ScaffoldApp.isMobile() ? OpportunityMobileEditView.instance() : OpportunityDesktopEditView.instance(), activity, proxyId);
    }
}
