// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.OutcomeDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.OutcomeDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.OutcomeDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.OutcomeMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.OutcomeMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.OpportunityProxy;
import eu.musesproject.server.rt2ae.client.proxy.OutcomeProxy;
import eu.musesproject.server.rt2ae.client.proxy.ThreatProxy;
import eu.musesproject.server.rt2ae.client.request.OutcomeRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;

public abstract class OutcomeActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        OutcomeDesktopEditView.instance().setCreating(true);
        Activity activity = new OutcomeEditActivity(null, factory, ScaffoldApp.isMobile() ? OutcomeMobileEditView.instance() : OutcomeDesktopEditView.instance(), placeController);
        return new OutcomeEditActivityWrapper(factory, ScaffoldApp.isMobile() ? OutcomeMobileEditView.instance() : OutcomeDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<OutcomeProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<OutcomeProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        OutcomeDesktopEditView.instance().setCreating(false);
        EntityProxyId<OutcomeProxy> proxyId = coerceId(place);
        Activity activity = new OutcomeEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? OutcomeMobileEditView.instance() : OutcomeDesktopEditView.instance(), placeController);
        return new OutcomeEditActivityWrapper(factory, ScaffoldApp.isMobile() ? OutcomeMobileEditView.instance() : OutcomeDesktopEditView.instance(), activity, proxyId);
    }
}
