// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.RiskcommunicationDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.RiskcommunicationDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.RiskcommunicationDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.DecisionSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.RisktreatmentSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.RiskcommunicationMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.RiskcommunicationMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.DecisionProxy;
import eu.musesproject.server.rt2ae.client.proxy.RiskcommunicationProxy;
import eu.musesproject.server.rt2ae.client.proxy.RisktreatmentProxy;
import eu.musesproject.server.rt2ae.client.request.RiskcommunicationRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.Set;

public abstract class RiskcommunicationActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        RiskcommunicationDesktopEditView.instance().setCreating(true);
        Activity activity = new RiskcommunicationEditActivity(null, factory, ScaffoldApp.isMobile() ? RiskcommunicationMobileEditView.instance() : RiskcommunicationDesktopEditView.instance(), placeController);
        return new RiskcommunicationEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RiskcommunicationMobileEditView.instance() : RiskcommunicationDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<RiskcommunicationProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<RiskcommunicationProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        RiskcommunicationDesktopEditView.instance().setCreating(false);
        EntityProxyId<RiskcommunicationProxy> proxyId = coerceId(place);
        Activity activity = new RiskcommunicationEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? RiskcommunicationMobileEditView.instance() : RiskcommunicationDesktopEditView.instance(), placeController);
        return new RiskcommunicationEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RiskcommunicationMobileEditView.instance() : RiskcommunicationDesktopEditView.instance(), activity, proxyId);
    }
}
