// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.RiskPolicyDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.RiskPolicyDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.RiskPolicyDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.RiskPolicyMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.RiskPolicyMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.RiskPolicyProxy;
import eu.musesproject.server.rt2ae.client.request.RiskPolicyRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;

public abstract class RiskPolicyActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        RiskPolicyDesktopEditView.instance().setCreating(true);
        Activity activity = new RiskPolicyEditActivity(null, factory, ScaffoldApp.isMobile() ? RiskPolicyMobileEditView.instance() : RiskPolicyDesktopEditView.instance(), placeController);
        return new RiskPolicyEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RiskPolicyMobileEditView.instance() : RiskPolicyDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<RiskPolicyProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<RiskPolicyProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        RiskPolicyDesktopEditView.instance().setCreating(false);
        EntityProxyId<RiskPolicyProxy> proxyId = coerceId(place);
        Activity activity = new RiskPolicyEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? RiskPolicyMobileEditView.instance() : RiskPolicyDesktopEditView.instance(), placeController);
        return new RiskPolicyEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RiskPolicyMobileEditView.instance() : RiskPolicyDesktopEditView.instance(), activity, proxyId);
    }
}
