// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import eu.musesproject.server.rt2ae.client.managed.activity.SecurityIncidentEditActivityWrapper.View;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.SecurityIncidentEditView;
import eu.musesproject.server.rt2ae.client.proxy.AssetProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import eu.musesproject.server.rt2ae.client.scaffold.activity.IsScaffoldMobileActivity;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyEditView;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListPlace;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

public abstract class SecurityIncidentEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setAssetsIdPickerValues(Collections.<AssetProxy>emptyList());
        requests.assetRequest().findAssetEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AssetProxyRenderer.instance().getPaths()).fire(new Receiver<List<AssetProxy>>() {

            public void onSuccess(List<AssetProxy> response) {
                List<AssetProxy> values = new ArrayList<AssetProxy>();
                values.add(null);
                values.addAll(response);
                view.setAssetsIdPickerValues(values);
            }
        });
        view.setDevicesIdPickerValues(Collections.<DeviceProxy>emptyList());
        requests.deviceRequest().findDeviceEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.DeviceProxyRenderer.instance().getPaths()).fire(new Receiver<List<DeviceProxy>>() {

            public void onSuccess(List<DeviceProxy> response) {
                List<DeviceProxy> values = new ArrayList<DeviceProxy>();
                values.add(null);
                values.addAll(response);
                view.setDevicesIdPickerValues(values);
            }
        });
        view.setUsersIdPickerValues(Collections.<UserProxy>emptyList());
        requests.userRequest().findUserEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.UserProxyRenderer.instance().getPaths()).fire(new Receiver<List<UserProxy>>() {

            public void onSuccess(List<UserProxy> response) {
                List<UserProxy> values = new ArrayList<UserProxy>();
                values.add(null);
                values.addAll(response);
                view.setUsersIdPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends eu.musesproject.server.rt2ae.client.managed.ui.SecurityIncidentEditView<V>> extends SecurityIncidentEditView<V> {

        void setAssetsIdPickerValues(Collection<AssetProxy> values);

        void setDevicesIdPickerValues(Collection<DeviceProxy> values);

        void setUsersIdPickerValues(Collection<UserProxy> values);
    }
}
