// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import eu.musesproject.server.rt2ae.client.managed.activity.UserEditActivityWrapper.View;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.UserEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.DeviceSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.SecurityIncidentSetEditor;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.DeviceProxy;
import eu.musesproject.server.rt2ae.client.proxy.SecurityIncidentProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserProxy;
import eu.musesproject.server.rt2ae.client.scaffold.activity.IsScaffoldMobileActivity;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyEditView;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyListPlace;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;

public abstract class UserEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setAccessrequestsPickerValues(Collections.<AccessrequestProxy>emptyList());
        requests.accessrequestRequest().findAccessrequestEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.AccessrequestProxyRenderer.instance().getPaths()).fire(new Receiver<List<AccessrequestProxy>>() {

            public void onSuccess(List<AccessrequestProxy> response) {
                List<AccessrequestProxy> values = new ArrayList<AccessrequestProxy>();
                values.add(null);
                values.addAll(response);
                view.setAccessrequestsPickerValues(values);
            }
        });
        view.setDevicesPickerValues(Collections.<DeviceProxy>emptyList());
        requests.deviceRequest().findDeviceEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.DeviceProxyRenderer.instance().getPaths()).fire(new Receiver<List<DeviceProxy>>() {

            public void onSuccess(List<DeviceProxy> response) {
                List<DeviceProxy> values = new ArrayList<DeviceProxy>();
                values.add(null);
                values.addAll(response);
                view.setDevicesPickerValues(values);
            }
        });
        view.setSecurityIncidentsPickerValues(Collections.<SecurityIncidentProxy>emptyList());
        requests.securityIncidentRequest().findSecurityIncidentEntries(0, 50).with(eu.musesproject.server.rt2ae.client.managed.ui.renderer.SecurityIncidentProxyRenderer.instance().getPaths()).fire(new Receiver<List<SecurityIncidentProxy>>() {

            public void onSuccess(List<SecurityIncidentProxy> response) {
                List<SecurityIncidentProxy> values = new ArrayList<SecurityIncidentProxy>();
                values.add(null);
                values.addAll(response);
                view.setSecurityIncidentsPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends eu.musesproject.server.rt2ae.client.managed.ui.UserEditView<V>> extends UserEditView<V> {

        void setAccessrequestsPickerValues(Collection<AccessrequestProxy> values);

        void setDevicesPickerValues(Collection<DeviceProxy> values);

        void setSecurityIncidentsPickerValues(Collection<SecurityIncidentProxy> values);
    }
}
