// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import eu.musesproject.server.rt2ae.client.managed.request.ApplicationRequestFactory;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.UserActionDesktopDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.UserActionDesktopEditView;
import eu.musesproject.server.rt2ae.client.managed.ui.desktop.UserActionDesktopListView;
import eu.musesproject.server.rt2ae.client.managed.ui.editor.AccessrequestSetEditor;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.UserActionMobileDetailsView;
import eu.musesproject.server.rt2ae.client.managed.ui.mobile.UserActionMobileEditView;
import eu.musesproject.server.rt2ae.client.proxy.AccessrequestProxy;
import eu.musesproject.server.rt2ae.client.proxy.UserActionProxy;
import eu.musesproject.server.rt2ae.client.request.UserActionRequest;
import eu.musesproject.server.rt2ae.client.scaffold.ScaffoldApp;
import eu.musesproject.server.rt2ae.client.scaffold.place.ProxyPlace;
import java.util.Set;

public abstract class UserActionActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        UserActionDesktopEditView.instance().setCreating(true);
        Activity activity = new UserActionEditActivity(null, factory, ScaffoldApp.isMobile() ? UserActionMobileEditView.instance() : UserActionDesktopEditView.instance(), placeController);
        return new UserActionEditActivityWrapper(factory, ScaffoldApp.isMobile() ? UserActionMobileEditView.instance() : UserActionDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<UserActionProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<UserActionProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        UserActionDesktopEditView.instance().setCreating(false);
        EntityProxyId<UserActionProxy> proxyId = coerceId(place);
        Activity activity = new UserActionEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? UserActionMobileEditView.instance() : UserActionDesktopEditView.instance(), placeController);
        return new UserActionEditActivityWrapper(factory, ScaffoldApp.isMobile() ? UserActionMobileEditView.instance() : UserActionDesktopEditView.instance(), activity, proxyId);
    }
}
