// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package eu.musesproject.server.rt2ae.client.managed.request;
import eu.musesproject.server.rt2ae.client.request.AccessrequestRequest;
import eu.musesproject.server.rt2ae.client.request.AssetRequest;
import eu.musesproject.server.rt2ae.client.request.ClueRequest;
import eu.musesproject.server.rt2ae.client.request.DecisionRequest;
import eu.musesproject.server.rt2ae.client.request.DeviceRequest;
import eu.musesproject.server.rt2ae.client.request.DeviceSecurityStateRequest;
import eu.musesproject.server.rt2ae.client.request.OpportunityRequest;
import eu.musesproject.server.rt2ae.client.request.OutcomeRequest;
import eu.musesproject.server.rt2ae.client.request.RiskPolicyRequest;
import eu.musesproject.server.rt2ae.client.request.RiskcommunicationRequest;
import eu.musesproject.server.rt2ae.client.request.RiskinformationRequest;
import eu.musesproject.server.rt2ae.client.request.RisktreatmentRequest;
import eu.musesproject.server.rt2ae.client.request.SecurityIncidentRequest;
import eu.musesproject.server.rt2ae.client.request.ThreatRequest;
import eu.musesproject.server.rt2ae.client.request.UserActionRequest;
import eu.musesproject.server.rt2ae.client.request.UserRequest;
import eu.musesproject.server.rt2ae.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    AccessrequestRequest accessrequestRequest();

    AssetRequest assetRequest();

    ClueRequest clueRequest();

    DecisionRequest decisionRequest();

    DeviceRequest deviceRequest();

    DeviceSecurityStateRequest deviceSecurityStateRequest();

    OpportunityRequest opportunityRequest();

    OutcomeRequest outcomeRequest();

    RiskPolicyRequest riskPolicyRequest();

    RiskcommunicationRequest riskcommunicationRequest();

    RiskinformationRequest riskinformationRequest();

    RisktreatmentRequest risktreatmentRequest();

    SecurityIncidentRequest securityIncidentRequest();

    ThreatRequest threatRequest();

    UserActionRequest userActionRequest();

    UserRequest userRequest();
}
